<a href="https://colab.research.google.com/github/ItzMeLeo/DAI6-Data-Exploration/blob/main/Data_Exploration_%26_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [ ]:
import os
import pandas as pd

# Loading and Parsing
Loading the data and parsing it into the correct format.

In [ ]:
# Cloning my repository from GitHub to get the csv
!git clone https://github.com/ItzMeLeo/DAI6-Data-Exploration.git

Cloning into 'DAI6-Data-Exploration'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), 9.36 MiB | 22.82 MiB/s, done.

In [ ]:
# Changing the current working directory
base_dir = "/content/DAI6-Data-Exploration"
os.chdir(base_dir)

os.getcwd()

'/content/DAI6-Data-Exploration'

In [ ]:
# Loading the data into a Pandas DataFrame
data = pd.read_csv("data/Data.csv")

data.head(10)

,Unnamed: 0,InputC1,InputC2,InputC3,InputC4,InputC5,InputC6,InputC7,InputC8,InputC9,...,InputA4,InputA5,InputA6,InputB1,InputB2,InputB3,InputB4,InputB5,InputB6,Target
0,2022-01-01 00:00:00,18.49650,18.81396,100.0696,618.6791,NaN,1931.360,7.272931,1878.295,1.549485,...,60.10090,7.385031,7.081979,27.39823,20.896960,260.1674,2.193955,NaN,6.236635,NaN
1,2022-01-01 00:05:00,18.49731,18.70401,100.0715,613.7349,NaN,1929.365,7.273591,1878.252,1.552745,...,60.09105,7.375766,7.136544,27.07825,26.921650,259.9575,2.187813,NaN,6.238485,NaN
2,2022-01-01 00:10:00,18.49693,18.59405,100.0733,608.7906,NaN,1924.322,7.274251,1878.209,1.556006,...,60.08120,7.366502,7.085941,26.75828,14.013700,259.7475,2.181671,NaN,6.240336,NaN
3,2022-01-01 00:15:00,18.49603,18.48410,100.0751,603.8464,NaN,1919.279,7.274910,1878.167,1.559266,...,60.07135,7.357237,6.743883,26.50328,5.789380,259.5375,2.175529,NaN,6.242187,NaN
4,2022-01-01 00:20:00,18.49512,18.37415,100.0770,598.9022,NaN,1914.235,7.275570,1878.124,1.562526,...,60.06150,7.347972,6.621848,26.29828,39.279620,259.3275,2.169388,NaN,6.244037,NaN
5,2022-01-01 00:25:00,18.49422,18.26419,100.0788,593.9580,NaN,1909.192,7.276230,1878.082,1.565786,...,60.05165,7.338707,6.721153,26.09327,23.755100,259.1176,2.163246,NaN,6.245887,NaN
6,2022-01-01 00:30:00,18.49332,18.15424,100.0806,589.0138,NaN,1904.149,7.276890,1878.039,1.569046,...,60.04180,7.329443,6.820458,26.13555,21.815950,258.9076,2.157104,NaN,6.247738,NaN
7,2022-01-01 00:35:00,18.49242,18.04429,100.0825,584.0696,NaN,1899.105,7.277550,1877.996,1.572307,...,60.03194,7.320178,6.919763,26.24025,12.932980,258.6976,2.150962,NaN,6.249588,NaN
8,2022-01-01 00:40:00,18.49152,17.93433,100.0843,579.1254,NaN,1894.062,7.278210,1877.954,1.575567,...,60.02209,7.310913,7.019067,26.34495,9.187466,258.4877,2.144820,NaN,6.251439,NaN
9,2022-01-01 00:45:00,18.49061,17.82438,100.0861,574.1812,NaN,1889.019,7.278870,1877.932,1.578827,...,60.01225,7.159253,7.118372,26.44965,16.867270,258.2777,2.138679,NaN,6.253290,NaN

# General Statistics
- mean,
- mode,
- std,
- % missing values,
etc.

What do we learn from these statistics?

In [ ]:
data.describe()

,InputC1,InputC2,InputC3,InputC4,InputC5,InputC6,InputC7,InputC8,InputC9,InputC10,...,InputA4,InputA5,InputA6,InputB1,InputB2,InputB3,InputB4,InputB5,InputB6,Target
count,71948.000000,70943.000000,71116.000000,76396.000000,67461.000000,70914.000000,70852.000000,70828.000000,70880.000000,70802.000000,...,66850.000000,68696.000000,70885.000000,72680.000000,72699.000000,76384.000000,66949.000000,43166.000000,72619.000000,70286.000000
mean,19.325297,29.442883,93.863525,780.417599,26.561597,1642.565742,7.301294,1828.115365,1.508127,26.336182,...,59.699607,21.657719,6.908254,26.188548,29.984823,162.424002,2.354799,3.900894,6.403803,51.028149
std,3.070935,14.328902,12.396636,302.515266,24.441761,224.266875,0.107335,178.147011,0.286217,2.941960,...,16.229842,14.842940,0.677970,5.113613,12.037443,100.029154,1.018617,3.004549,0.662469,44.037615
min,15.776370,-3.444384,-3.925755,0.000000,16.312110,-6.275873,6.923481,2.695313,0.212584,15.622140,...,-0.008789,-1.603601,1.995943,12.242630,-0.770695,-11.200000,0.007180,-0.146004,2.717968,-0.011699
25%,17.417635,21.397670,89.799840,558.980425,17.379560,1510.113500,7.246059,1834.160500,1.434766,24.744620,...,51.859820,12.269283,6.728139,22.493372,21.526345,88.491798,1.647085,1.903508,6.093094,21.311235
50%,18.035935,29.123960,99.758640,729.260500,17.498360,1730.261000,7.254542,1864.196000,1.502118,26.469720,...,62.029675,16.291395,6.885195,26.071815,28.376370,149.603250,2.257355,3.267908,6.443357,33.956840
75%,18.547920,36.778240,100.079000,1006.964500,18.246240,1785.910000,7.275279,1893.737250,1.569042,28.105180,...,70.907692,31.088035,7.030548,29.840980,36.752415,219.925925,2.842530,5.219162,6.783164,62.185650
max,25.530860,515.131300,248.376300,1557.484000,95.200650,2862.818000,8.438206,2059.961000,5.339407,35.171540,...,92.420960,135.645300,12.246300,45.250710,127.795700,571.200000,10.165010,39.298890,8.939406,203.460900

In [ ]:
# Checking the amount of NaNs per column
nans = data.isna().sum()
nans

Unnamed: 0        0
InputC1        4526
InputC2        5531
InputC3        5358
InputC4          78
InputC5        9013
InputC6        5560
InputC7        5622
InputC8        5646
InputC9        5594
InputC10       5672
InputE1        5603
InputE2        1887
InputE3       43354
InputD1        4551
InputD2        5284
InputD3        5336
InputD4          76
InputD5       10121
InputD6        5593
InputD7        5346
InputD8        5588
InputD9        1587
InputD10       5582
InputA1         724
InputA2       25422
InputA3         169
InputA4        9624
InputA5        7778
InputA6        5589
InputB1        3794
InputB2        3775
InputB3          90
InputB4        9525
InputB5       33308
InputB6        3855
Target         6188
dtype: int64

In [ ]:
# Percentage of missing values per column
percent_missing = nans * 100 / len(data)
percent_missing

Unnamed: 0     0.000000
InputC1        5.918351
InputC2        7.232523
InputC3        7.006303
InputC4        0.101995
InputC5       11.785705
InputC6        7.270445
InputC7        7.351518
InputC8        7.382901
InputC9        7.314904
InputC10       7.416900
InputE1        7.326673
InputE2        2.467505
InputE3       56.691163
InputD1        5.951042
InputD2        6.909538
InputD3        6.977535
InputD4        0.099380
InputD5       13.234563
InputD6        7.313597
InputD7        6.990611
InputD8        7.307059
InputD9        2.075215
InputD10       7.299213
InputA1        0.946727
InputA2       33.242671
InputA3        0.220990
InputA4       12.584669
InputA5       10.170777
InputA6        7.308366
InputB1        4.961163
InputB2        4.936318
InputB3        0.117687
InputB4       12.455214
InputB5       43.554672
InputB6        5.040929
Target         8.091639
dtype: float64

# Outliers
Exploring the outliers.

## Exploring Outliers
Explaining why certain data is treated as an outlier, e.g. because it is physically impossible.

## Removing Outliers
Explaining how to remove the outliers.

# Data Distributions
Exploring the data distributions.

# Time Series Analysis
Example: seasonality.

# Correlations

## Linear Correlations
Exploring the correlations between all the variables, including target.

## Target Correlations
Exploring the correlations (not only linear) with the other variables.

# Preprocessing
A pipeline that converts the raw data into the data needed by the model.

# Modelling

## Choice of Model
Why was this particular model chosen to solve the use case?

## Train-test split
Stating the train-test split.

## Training the Model
Training the AI-Model.

## Hyperparametertuning

# Results
Discussing the performance of the AI-Model.

## If I had more time, ...

### what would I do differently?

### where would I spend more time on to improve the result?

## Other reflections